name: rpk-drinks-brewery-bukkit
author: alyphen
version: @version@
main: com.rpkit.drinks.bukkit.brewery.RPKDrinksBreweryBukkit
depend:
- Brewery
- rpk-core-bukkit
- rpk-player-lib-bukkit
- rpk-character-lib-bukkit
- rpk-drink-lib-bukkit